# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de egreso',
                'verbose_name_plural': 'Categorías de egreso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoriaegreso')),
            ],
            options={
                'verbose_name': 'Costo fijo mensual',
                'verbose_name_plural': 'Costos fijos mensuales',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(max_length=200)),
                ('automatico', models.BooleanField(default=False, editable=False)),
                ('origen', models.CharField(blank=True, editable=False, help_text='Referencia al registro que lo originó (modelo:id).', max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='finanzas.categoriaegreso')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('origen', ''), _negated=True), fields=('origen',), name='egreso_origen_unico')],
            },
        ),
    ]
