# Generated by Django 5.2.18 on 2026-10-08 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaegreso',
            name='tolerancia_presupuesto',
            field=models.PositiveSmallIntegerField(default=10, help_text='Verde hasta el presupuesto; amarillo hasta presupuesto + tolerancia; rojo después.', verbose_name='Tolerancia sobre el presupuesto (%)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='cargado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='comprobante',
            field=models.FileField(blank=True, upload_to='egresos/%Y/%m/', verbose_name='Archivo del comprobante'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=40, verbose_name='N° de factura / comprobante'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='proveedor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='finanzas.categoriaegreso')),
            ],
            options={
                'ordering': ['mes', 'categoria__nombre'],
                'unique_together': {('categoria', 'mes')},
            },
        ),
    ]
