# Generated by Django 5.2.18 on 2026-10-08 01:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_parametros_adicional_presentismo_and_more'),
        ('finanzas', '0002_categoriaegreso_tolerancia_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque / e-cheq'), ('tarjeta', 'Tarjeta'), ('debito', 'Débito automático')], max_length=15),
        ),
        migrations.AddField(
            model_name='egreso',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura', 'Factura'), ('ticket', 'Ticket'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito'), ('otro', 'Otro')], default='factura', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vence el'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('cuit', models.CharField(blank=True, max_length=13, verbose_name='CUIT')),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría habitual de sus comprobantes (se propone al cargar).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.categoriaegreso')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='proveedor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='finanzas.proveedor', verbose_name='Proveedor (ficha)'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes liquidado.')),
                ('basico', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('horas_extra_50', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='HE al 50 % (h)')),
                ('horas_extra_100', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='HE al 100 % (h)')),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('presentismo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Adicional presentismo')),
                ('otros_adicionales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('multas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Descuento por multas')),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cargas_sociales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Costo para la empresa')),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('faltas_injustificadas', models.PositiveSmallIntegerField(default=0)),
                ('tardanzas', models.PositiveSmallIntegerField(default=0)),
                ('recibo', models.FileField(blank=True, upload_to='recibos/%Y/%m/', verbose_name='Recibo de sueldo firmado')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='borrador', max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.persona')),
            ],
            options={
                'verbose_name': 'Liquidación (pre-liquidación de sueldo)',
                'verbose_name_plural': 'Liquidaciones (pre-liquidación de sueldos)',
                'ordering': ['-periodo', 'persona__apellido'],
                'unique_together': {('persona', 'periodo')},
            },
        ),
    ]
