# Generated by Django 5.2.18 on 2026-10-08 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_proveedores_desde_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='descuento_dias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Descuento por días no trabajados'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='dias_descuento',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Faltas sin justificar + días de suspensión.', max_digits=5, verbose_name='Días no trabajados a descontar'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='multas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Multas registradas (informativo, no se descuentan: art. 131 LCT)'),
        ),
    ]
