# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('cada_km', models.PositiveIntegerField(blank=True, null=True)),
                ('cada_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Tipo de service',
                'verbose_name_plural': 'Tipos de service',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('km_actual', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('taller', 'En taller'), ('fuera', 'Fuera de servicio')], default='operativo', max_length=10)),
                ('vencimiento_vtv', models.DateField(blank=True, null=True, verbose_name='Vencimiento VTV')),
                ('vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='core.persona')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('km', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taller', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.tiposervice')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Service realizado',
                'verbose_name_plural': 'Services realizados',
                'ordering': ['-fecha'],
            },
        ),
    ]
