# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('material', 'Material / consumible'), ('equipo', 'Equipo (decodificador, módem, etc.)'), ('repuesto', 'Repuesto')], default='material', max_length=20)),
                ('unidad', models.CharField(default='u', max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('es_decodificador', models.BooleanField(default=False, help_text='Se usa para la proyección de decodificadores de TV.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Materiales y equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DemandaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad_clientes', models.PositiveIntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.tipotarea')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zona')),
            ],
            options={
                'verbose_name': 'Demanda comercial prevista',
                'verbose_name_plural': 'Demanda comercial prevista',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('remito', models.CharField(blank=True, max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Ingreso de stock (lote)',
                'verbose_name_plural': 'Ingresos de stock (lotes)',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(choices=[('consumo', 'Consumo en orden de trabajo'), ('entrega', 'Entrega a técnico (stock en mano)'), ('devolucion', 'Devolución a proveedor'), ('baja', 'Baja / rotura / pérdida')], default='consumo', max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.material')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='operaciones.ordentrabajo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_material', to='core.persona')),
            ],
            options={
                'verbose_name': 'Salida de stock',
                'verbose_name_plural': 'Salidas de stock',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_recetas', to='inventario.material')),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='operaciones.tipotarea')),
            ],
            options={
                'verbose_name': 'Material por tipo de tarea',
                'verbose_name_plural': 'Materiales por tipo de tarea',
                'unique_together': {('tipo_tarea', 'material')},
            },
        ),
    ]
