# Generated by Django 5.2.18 on 2026-10-07 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_latitud_cliente_longitud_cliente_telefono_and_more'),
        ('inventario', '0001_initial'),
        ('operaciones', '0002_ordentrabajo_conforme_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado (a preparar)'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('respuesta', models.CharField(blank=True, max_length=200)),
                ('entregado', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprobados', to='core.persona')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_material', to='core.persona')),
            ],
            options={
                'verbose_name': 'Pedido de materiales',
                'verbose_name_plural': 'Pedidos de materiales',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.pedidomaterial')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStockTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega del depósito'), ('consumo', 'Consumo en orden'), ('devolucion', 'Devolución al depósito'), ('ajuste', 'Ajuste de inventario')], max_length=12)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo entra, negativo sale.', max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tecnico', to='inventario.material')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.ordentrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='core.persona')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.pedidomaterial')),
            ],
            options={
                'verbose_name': 'Movimiento de stock del técnico',
                'verbose_name_plural': 'Movimientos de stock de técnicos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
