# Generated by Django 5.2.18 on 2026-10-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_pedidomaterial_pedidoitem_movimientostocktecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomaterial',
            name='resuelto',
            field=models.DateTimeField(blank=True, help_text='Cuándo el supervisor lo aprobó o rechazó.', null=True),
        ),
    ]
