# Generated by Django 5.2.18 on 2026-10-07 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_parametros_deuda_dias_aviso_and_more'),
        ('inventario', '0003_pedidomaterial_resuelto'),
        ('operaciones', '0002_ordentrabajo_conforme_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=60)),
                ('fecha_retiro', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('en_tecnico', 'En poder del técnico'), ('devuelto', 'Devuelto al depósito'), ('extraviado', 'Extraviado')], db_index=True, default='en_tecnico', max_length=12)),
                ('devuelto', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('material', models.ForeignKey(blank=True, help_text='Tipo de equipo (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.material')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_retirados', to='operaciones.ordentrabajo')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_recibidos', to='core.persona')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_retirados', to='core.persona')),
            ],
            options={
                'verbose_name': 'Equipo retirado a cliente',
                'verbose_name_plural': 'Equipos retirados a clientes',
                'ordering': ['fecha_retiro'],
            },
        ),
    ]
