# Generated by Django 5.2.18 on 2026-10-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equiporetirado'),
        ('operaciones', '0003_ordentrabajo_conforme_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomaterial',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Llamada para la que se piden las partes (LOM).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='operaciones.ordentrabajo'),
        ),
    ]
