# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('epp', 'Elemento de protección personal'), ('herramienta', 'Herramienta'), ('critico', 'Material crítico de seguridad')], default='epp', max_length=20)),
                ('vida_util_dias', models.PositiveIntegerField(blank=True, help_text='Días hasta reemplazo obligatorio (vacío = sin vencimiento).', null=True)),
                ('obligatorio_tecnicos', models.BooleanField(default=False, help_text='Todo técnico en calle debe tenerlo asignado y vigente.')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Unidades en pañol para entregar.')),
            ],
            options={
                'verbose_name': 'Herramienta / EPP',
                'verbose_name_plural': 'Herramientas / EPP',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.localdate)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField(blank=True, editable=False, null=True)),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('devuelto', 'Devuelto'), ('perdido', 'Perdido'), ('danado', 'Dañado / reemplazado')], default='en_uso', max_length=10)),
                ('conformidad_firmada', models.BooleanField(default=False, help_text='El técnico firmó/confirmó la recepción (en la app).')),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.persona')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='herramientas.elemento')),
            ],
            options={
                'verbose_name': 'Asignación de herramienta / EPP',
                'verbose_name_plural': 'Asignaciones de herramientas / EPP',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
