# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_max_stock', models.PositiveIntegerField(default=60, help_text='Un lote con más días que esto sin consumirse genera alerta crítica.', verbose_name='Días máximos de stock parado')),
                ('dias_aviso_stock', models.PositiveIntegerField(default=45, help_text="A partir de estos días el lote aparece como 'por vencer'.", verbose_name='Días de aviso previo')),
                ('hectareas_dia_min', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='Hectáreas por cuadrilla/día (mín.)')),
                ('hectareas_dia_max', models.DecimalField(decimal_places=2, default=Decimal('6'), max_digits=5, verbose_name='Hectáreas por cuadrilla/día (máx.)')),
                ('clientes_por_tecnico_dia', models.DecimalField(decimal_places=2, default=Decimal('6'), help_text='Tope operativo de visitas diarias por técnico.', max_digits=5, verbose_name='Clientes atendibles por técnico/día')),
                ('prob_decodificador_min', models.DecimalField(decimal_places=3, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Prob. de pedido de decodificador (escenario bajo)')),
                ('prob_decodificador_max', models.DecimalField(decimal_places=3, default=Decimal('0.60'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Prob. de pedido de decodificador (escenario alto)')),
                ('dias_ventana_evaluacion', models.PositiveIntegerField(default=90, verbose_name='Ventana de evaluación de técnicos (días)')),
                ('dias_cobertura_stock_min', models.PositiveIntegerField(default=7, help_text='Si el stock alcanza para menos días que esto, se alerta faltante.', verbose_name='Días mínimos de cobertura de stock')),
            ],
            options={
                'verbose_name': 'Parámetros del sistema',
                'verbose_name_plural': 'Parámetros del sistema',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('densidad_clientes_ha', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Densidad promedio usada para traducir hectáreas cubiertas en clientes.', max_digits=6, verbose_name='Clientes por hectárea')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('stock', 'Inventario / stock'), ('flota', 'Flota'), ('epp', 'Herramientas / EPP'), ('tecnicos', 'Técnicos'), ('supervision', 'Supervisión'), ('incidentes', 'Incidentes'), ('finanzas', 'Finanzas')], max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('aviso', 'Aviso'), ('critica', 'Crítica')], default='aviso', max_length=10)),
                ('clave', models.CharField(help_text='Identificador estable para no duplicar la misma alerta.', max_length=120)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('resuelta', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['resuelta', '-nivel', '-actualizada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resuelta', False)), fields=('clave',), name='alerta_abierta_unica')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('supervisor', 'Supervisor'), ('administrativo', 'Administrativo'), ('gerencia', 'Gerencia')], default='tecnico', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_cargo', to='core.persona')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='core.zona')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° de cliente')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('moderno', 'Moderno (fibra/smart)'), ('comercial', 'Comercial')], default='residencial', max_length=20)),
                ('cantidad_televisores', models.PositiveSmallIntegerField(default=1)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.zona')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
