# Generated by Django 5.2.18 on 2026-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='tecnicos_por_cuadrilla',
            field=models.PositiveSmallIntegerField(default=2, help_text='Las hectáreas/día se miden por cuadrilla; esto convierte técnicos en cuadrillas.', verbose_name='Técnicos por cuadrilla'),
        ),
    ]
