# Generated by Django 5.2.18 on 2026-10-07 21:39

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametros_tecnicos_por_cuadrilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='destinatarios_parte',
            field=models.TextField(blank=True, help_text='Uno por línea. Los supervisores reciben además el parte de su equipo en su propio mail.', verbose_name='Mails que reciben el parte diario completo'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='horas_jornada',
            field=models.DecimalField(decimal_places=1, default=Decimal('8'), max_digits=4, verbose_name='Horas de una jornada normal'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='tolerancia_tarde_minutos',
            field=models.PositiveIntegerField(default=10, verbose_name='Tolerancia de llegada tarde (minutos)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='usar_hectareas',
            field=models.BooleanField(default=False, help_text='Opcional. Si está apagado, la capacidad se calcula sólo por clientes por técnico.', verbose_name='Medir hectáreas cubiertas'),
        ),
        migrations.AddField(
            model_name='persona',
            name='hora_entrada',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Horario de entrada'),
        ),
        migrations.AddField(
            model_name='persona',
            name='hora_salida',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Horario de salida'),
        ),
        migrations.AddField(
            model_name='persona',
            name='motivo_egreso',
            field=models.CharField(blank=True, choices=[('renuncia', 'Renuncia'), ('despido', 'Despido'), ('despido_causa', 'Despido con causa'), ('fin_contrato', 'Fin de contrato'), ('jubilacion', 'Jubilación'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='trabaja_sabados',
            field=models.BooleanField(default=True),
        ),
    ]
