# Generated by Django 5.2.18 on 2026-10-07 21:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametros_destinatarios_parte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='horas_jornada',
            field=models.DecimalField(decimal_places=1, default=Decimal('9'), help_text='Lo que exceda esto entre entrada y salida cuenta como hora extra.', max_digits=4, verbose_name='Horas de una jornada normal (incluye almuerzo)'),
        ),
    ]
