# Generated by Django 5.2.18 on 2026-10-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_horas_jornada_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='modulo',
            field=models.CharField(choices=[('personal', 'Personal / asistencia'), ('stock', 'Inventario / stock'), ('flota', 'Flota'), ('epp', 'Herramientas / EPP'), ('tecnicos', 'Técnicos'), ('supervision', 'Supervisión'), ('incidentes', 'Incidentes'), ('finanzas', 'Finanzas')], max_length=20),
        ),
    ]
