# Generated by Django 5.2.18 on 2026-10-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alerta_modulo_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='parametros',
            name='encuesta_diaria',
            field=models.BooleanField(default=True, help_text='La encuesta corta de cada día. La evaluación semanal está siempre disponible.', verbose_name='Encuesta diaria al supervisor'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.persona')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to='core.persona')),
            ],
            options={
                'verbose_name': 'Suscripción a notificaciones',
                'verbose_name_plural': 'Suscripciones a notificaciones',
            },
        ),
    ]
