# Generated by Django 5.2.18 on 2026-10-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alerta_modulo_partes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('supervisor', 'Supervisor')], max_length=12)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(help_text='Qué mide y cómo se calcula.')),
                ('unidad', models.CharField(default='%', max_length=20)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimo', models.DecimalField(decimal_places=2, help_text="Valor que vale 0 puntos (si 'mayor es mejor' está apagado, es el máximo tolerable).", max_digits=8, verbose_name='Mínimo aceptable')),
                ('mayor_es_mejor', models.BooleanField(default=True)),
                ('peso', models.PositiveSmallIntegerField(default=10, help_text='Peso en el índice (0 = sólo informativo).')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicador de productividad',
                'verbose_name_plural': 'Indicadores de productividad',
                'ordering': ['rol', 'orden'],
            },
        ),
    ]
