# Generated by Django 5.2.18 on 2026-10-07 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_indicadores_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cambiar_clave', models.BooleanField(default=True, help_text='Al ingresar se le pide elegir una clave propia (primer ingreso o tras un blanqueo).')),
                ('ultimo_cambio_clave', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('acepto_privacidad', models.DateTimeField(blank=True, help_text='Cuándo aceptó el aviso de privacidad (uso de ubicación y datos).', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de usuario',
                'verbose_name_plural': 'Cuentas de usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_ingresado', models.CharField(blank=True, help_text="Lo que se escribió en 'usuario'.", max_length=150)),
                ('evento', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('fallido', 'Intento fallido'), ('bloqueo', 'Cuenta bloqueada'), ('cambio_clave', 'Cambio de clave'), ('blanqueo', 'Blanqueo de clave (gerencia)'), ('admin', 'Cambio de acceso (gerencia)')], max_length=15)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('hecho_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_sobre_accesos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registro de accesos',
                'ordering': ['-fecha'],
            },
        ),
    ]
