# Generated by Django 5.2.18 on 2026-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cuentas_y_accesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentausuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, help_text='Al ingresar se le pide elegir una clave propia (primer ingreso o tras un blanqueo).'),
        ),
    ]
