# Generated by Django 5.2.18 on 2026-10-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cuenta_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='deuda_dias_aviso',
            field=models.PositiveIntegerField(default=2, help_text='Una parte sin regularizar pasa a amarillo después de estos días.', verbose_name='Días para pasar a amarillo (partes adeudadas)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='deuda_dias_critico',
            field=models.PositiveIntegerField(default=5, help_text='Y a rojo después de estos días (además se avisa al supervisor).', verbose_name='Días para pasar a rojo (partes adeudadas)'),
        ),
    ]
