# Generated by Django 5.2.18 on 2026-10-07 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_parametros_deuda_dias_aviso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='indice_rojo',
            field=models.PositiveSmallIntegerField(default=55, verbose_name='Índice: rojo por debajo de'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='indice_verde',
            field=models.PositiveSmallIntegerField(default=75, verbose_name='Índice: verde desde'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='minimo',
            field=models.DecimalField(decimal_places=2, help_text='Más allá de este valor el indicador está en rojo (y vale 0 puntos).', max_digits=8, verbose_name='Límite (rojo)'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='rol',
            field=models.CharField(choices=[('mando', 'Tablero de mando'), ('tecnico', 'Técnico'), ('supervisor', 'Supervisor')], max_length=12),
        ),
        migrations.CreateModel(
            name='CambioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alcance', models.CharField(help_text='General o equipo de …', max_length=80)),
                ('antes', models.CharField(max_length=80)),
                ('despues', models.CharField(max_length=80)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de meta',
                'verbose_name_plural': 'Cambios de metas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite (rojo)')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_equipo', to='core.indicador')),
                ('supervisor', models.ForeignKey(limit_choices_to={'rol': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='metas_equipo', to='core.persona')),
            ],
            options={
                'verbose_name': 'Meta de equipo',
                'verbose_name_plural': 'Metas de equipo',
                'unique_together': {('supervisor', 'indicador')},
            },
        ),
    ]
