# Generated by Django 5.2.18 on 2026-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_metas_y_semaforos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='minimo',
            field=models.DecimalField(decimal_places=2, help_text='Más allá de este valor el indicador está en rojo (y vale 0 puntos).', max_digits=14, verbose_name='Límite (rojo)'),
        ),
    ]
