# Generated by Django 5.2.18 on 2026-10-08 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cliente_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('calculado', 'Calculado por el sistema'), ('manual', 'Carga manual (valor mensual)')], default='calculado', max_length=10),
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes al que corresponde.')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='core.indicador')),
                ('persona', models.ForeignKey(blank=True, help_text='Vacío = valor de toda la empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_indicador', to='core.persona')),
            ],
            options={
                'verbose_name': 'Valor de indicador manual',
                'verbose_name_plural': 'Valores de indicadores manuales',
                'ordering': ['-periodo'],
                'unique_together': {('indicador', 'persona', 'periodo')},
            },
        ),
    ]
