# Generated by Django 5.2.18 on 2026-10-08 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_indicadores_manuales'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='adicional_presentismo',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.33'), max_digits=5, verbose_name='Adicional por presentismo (% del básico)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='cargas_sociales',
            field=models.DecimalField(decimal_places=2, default=Decimal('26'), max_digits=5, verbose_name='Cargas sociales del empleador (%)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='horas_mensuales',
            field=models.PositiveSmallIntegerField(default=200, help_text='Para calcular el valor de la hora.', verbose_name='Horas mensuales de jornada completa'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='presentismo_tardanzas_max',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Llegadas tarde toleradas para cobrar presentismo'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='recargo_extra_100',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Recargo hora extra domingo/feriado (%)'),
        ),
        migrations.AddField(
            model_name='parametros',
            name='recargo_extra_50',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Recargo hora extra común (%)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='categoria_laboral',
            field=models.CharField(blank=True, max_length=80, verbose_name='Categoría / convenio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sueldo_basico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sólo lo ven gerencia y contabilidad.', max_digits=12, null=True, verbose_name='Sueldo básico mensual'),
        ),
    ]
