# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('calidad', 'Calidad de instalación'), ('seguridad', 'Seguridad / uso de EPP'), ('vehiculo', 'Estado de vehículo'), ('conducta', 'Conducta / trato al cliente')], default='calidad', max_length=20)),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntaje del trabajo controlado (1-5)')),
                ('desvio_detectado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.FileField(blank=True, upload_to='informes/%Y/%m/')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.ordentrabajo')),
                ('supervisor', models.ForeignKey(limit_choices_to={'rol': 'supervisor'}, on_delete=django.db.models.deletion.PROTECT, related_name='informes_realizados', to='core.persona')),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='informes_recibidos', to='core.persona')),
            ],
            options={
                'verbose_name': 'Informe de control',
                'verbose_name_plural': 'Informes de control',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recapacitacion', 'Recapacitación'), ('apercibimiento', 'Apercibimiento'), ('multa', 'Multa / descuento'), ('suspension', 'Suspensión'), ('charla', 'Charla / corrección en el momento')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo para multas.', max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('cumplida', models.BooleanField(default=False)),
                ('aplicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_aplicadas', to='core.persona')),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_correctivas', to='core.persona')),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='supervision.informecontrol')),
            ],
            options={
                'verbose_name': 'Acción correctiva',
                'verbose_name_plural': 'Acciones correctivas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TareaSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('descripcion', models.CharField(max_length=250)),
                ('meta', models.PositiveIntegerField(blank=True, help_text='Valor objetivo si es medible (ej: 8 controles).', null=True)),
                ('resultado', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplida', 'Cumplida'), ('parcial', 'Parcial'), ('no_cumplida', 'No cumplida')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'rol': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_supervisor', to='core.persona')),
            ],
            options={
                'verbose_name': 'Tarea / objetivo de supervisor',
                'verbose_name_plural': 'Tareas / objetivos de supervisores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('respondida', models.DateTimeField(blank=True, null=True)),
                ('trato', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Trato y respeto')),
                ('claridad', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Claridad de las indicaciones')),
                ('apoyo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Apoyo ante problemas')),
                ('presencia', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Presencia / disponibilidad')),
                ('comentario', models.TextField(blank=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_recibidas', to='core.persona')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_respondidas', to='core.persona')),
            ],
            options={
                'verbose_name': 'Encuesta diaria al supervisor',
                'verbose_name_plural': 'Encuestas diarias a supervisores',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'tecnico')},
            },
        ),
    ]
