# Generated by Django 5.2.18 on 2026-10-07 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_latitud_cliente_longitud_cliente_telefono_and_more'),
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(db_index=True, help_text='Lunes de la semana evaluada.')),
                ('respondida', models.DateTimeField(auto_now_add=True)),
                ('general', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación general de la semana')),
                ('trato', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Trato y respeto')),
                ('organizacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Organización y reparto del trabajo')),
                ('apoyo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Apoyo cuando hubo problemas')),
                ('ensenanza', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Te ayudó a mejorar / te enseñó')),
                ('justicia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Fue justo con el equipo')),
                ('lo_mejor', models.TextField(blank=True, verbose_name='Lo mejor de la semana')),
                ('a_mejorar', models.TextField(blank=True, verbose_name='Qué debería mejorar')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_semanales_recibidas', to='core.persona')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_semanales', to='core.persona')),
            ],
            options={
                'verbose_name': 'Evaluación semanal al supervisor',
                'verbose_name_plural': 'Evaluaciones semanales a supervisores',
                'ordering': ['-semana'],
                'unique_together': {('semana', 'tecnico')},
            },
        ),
    ]
