# Generated by Django 5.2.18 on 2026-10-08 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_encuestasemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncorrectiva',
            name='dias_suspension',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sólo para suspensiones: días sin goce.'),
        ),
        migrations.AlterField(
            model_name='accioncorrectiva',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sólo para multas. Ojo: no se descuentan del sueldo (art. 131 LCT).', max_digits=12),
        ),
    ]
