# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('rotura_vivienda', 'Rotura en vivienda'), ('cano_pinchado', 'Caño pinchado (agua/gas)'), ('cableado', 'Daño a cableado de terceros'), ('vehiculo', 'Accidente de vehículo'), ('lesion', 'Lesión de persona'), ('otro', 'Otro')], max_length=20)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('critica', 'Crítica')], default='grave', max_length=10)),
                ('responsabilidad_civil', models.BooleanField(default=True, help_text='¿Involucra responsabilidad civil de la empresa frente a terceros?')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('causa_raiz', models.TextField(blank=True, help_text='Por qué ocurrió (falta de capacitación, apuro, herramienta, etc.)')),
                ('plan_accion', models.TextField(blank=True, help_text='Cómo se mitiga y cómo se evita que se repita.')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monto_recuperado', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recuperado por seguro, descuento al responsable, etc.', max_digits=14)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_gestion', 'En gestión / negociación'), ('legal', 'Reclamo legal en curso'), ('cerrado', 'Cerrado')], db_index=True, default='abierto', max_length=15)),
                ('resolucion', models.CharField(choices=[('pendiente', 'Pendiente'), ('reparacion', 'Reparación a cargo de la empresa'), ('acuerdo', 'Acuerdo económico con el damnificado'), ('seguro', 'Cubierto por seguro'), ('juicio', 'Juicio'), ('rechazado', 'Reclamo rechazado (sin responsabilidad)')], default='pendiente', max_length=15)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.ordentrabajo')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_reportados', to='core.persona')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_supervisados', to='core.persona')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros', to='core.persona')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zona')),
            ],
            options={
                'verbose_name': 'Siniestro / incidente',
                'verbose_name_plural': 'Siniestros / incidentes',
                'ordering': ['-fecha'],
            },
        ),
    ]
