# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('horas', models.DecimalField(decimal_places=1, default=4, max_digits=5)),
                ('obligatorio', models.BooleanField(default=False)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capacitacion.competencia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('en_produccion', models.BooleanField(default=False, help_text='Capacitación en campo, acompañando al técnico en producción.')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='capacitacion.curso')),
            ],
            options={
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('nivel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.competencia')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='core.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.persona')),
            ],
            options={
                'verbose_name': 'Evaluación de competencia',
                'verbose_name_plural': 'Evaluaciones de competencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.capacitacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.persona')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'unique_together': {('capacitacion', 'persona')},
            },
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes',
            field=models.ManyToManyField(related_name='capacitaciones', through='capacitacion.Participacion', to='core.persona'),
        ),
    ]
