# Generated by Django 5.2.18 on 2026-10-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
        ('core', '0002_parametros_tecnicos_por_cuadrilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('productividad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('indice_productividad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('score_productividad', models.DecimalField(decimal_places=1, max_digits=5)),
                ('score_calidad', models.DecimalField(decimal_places=1, max_digits=5)),
                ('score_disciplina', models.DecimalField(decimal_places=1, max_digits=5)),
                ('score_seguridad', models.DecimalField(decimal_places=1, max_digits=5)),
                ('riesgo', models.DecimalField(decimal_places=1, max_digits=5)),
                ('diagnostico', models.CharField(max_length=60)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_evaluacion', to='core.persona')),
            ],
            options={
                'verbose_name': 'Evaluación histórica (semanal)',
                'verbose_name_plural': 'Evaluaciones históricas (semanales)',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'persona')},
            },
        ),
    ]
