# Generated by Django 5.2.18 on 2026-10-07 20:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('minutos_estandar', models.PositiveIntegerField(default=60, help_text='Tiempo estándar esperado para completar la tarea.')),
                ('puede_requerir_decodificador', models.BooleanField(default=False, help_text='Si en esta tarea el cliente puede pedir decodificador para TV.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de tarea',
                'verbose_name_plural': 'Tipos de tarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha_programada', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fecha_ejecucion', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('completada', 'Completada'), ('fallida', 'Fallida / no resuelta'), ('reprogramada', 'Reprogramada')], db_index=True, default='pendiente', max_length=20)),
                ('minutos_reales', models.PositiveIntegerField(blank=True, null=True)),
                ('decodificador_solicitado', models.BooleanField(default=False)),
                ('decodificadores_instalados', models.PositiveSmallIntegerField(default=0)),
                ('es_retrabajo', models.BooleanField(default=False, help_text='Visita para corregir un trabajo anterior mal hecho (indicador de calidad).')),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='core.cliente')),
                ('orden_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrabajos', to='operaciones.ordentrabajo')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='core.persona')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='operaciones.tipotarea')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_programada', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('en_calle', models.BooleanField(default=True, help_text='Salió a trabajar en calle ese día.')),
                ('motivo_ausencia', models.CharField(blank=True, max_length=100)),
                ('km_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('km_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('hectareas_cubiertas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, default=Decimal('8'), max_digits=4)),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='core.persona')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.vehiculo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zona')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'tecnico')},
            },
        ),
    ]
