# Generated by Django 5.2.18 on 2026-10-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='conforme_dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='Conformidad: DNI'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='conforme_nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Conformidad: nombre'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fin_trabajo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='firma',
            field=models.FileField(blank=True, upload_to='firmas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='foto_trabajo',
            field=models.FileField(blank=True, upload_to='ordenes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='inicio_trabajo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='lat_cierre',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='lng_cierre',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_no_resuelto',
            field=models.CharField(blank=True, choices=[('cliente_ausente', 'Cliente ausente'), ('falta_material', 'Faltó material'), ('problema_red', 'Problema de red / externo'), ('direccion', 'Dirección errónea'), ('clima', 'Clima'), ('rechazo', 'Cliente rechazó el trabajo'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='series_instaladas',
            field=models.CharField(blank=True, max_length=300, verbose_name='N° de serie instalados'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='series_retiradas',
            field=models.CharField(blank=True, max_length=300, verbose_name='N° de serie retirados'),
        ),
    ]
