# Generated by Django 5.2.18 on 2026-10-08 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cliente_email'),
        ('operaciones', '0002_ordentrabajo_conforme_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='conforme_apellido',
            field=models.CharField(blank=True, max_length=120, verbose_name='Conformidad: apellido'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='minutos_retorno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de retorno (min)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='minutos_viaje',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de viaje (min)'),
        ),
        migrations.CreateModel(
            name='GastoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Qué se compró')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.FileField(blank=True, upload_to='gastos/%Y/%m/', verbose_name='Factura / ticket')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado para reintegro'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='operaciones.ordentrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_orden', to='core.persona')),
            ],
            options={
                'verbose_name': 'Gasto de la orden',
                'verbose_name_plural': 'Gastos de las órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('cierre', 'Cierre (qué se hizo)'), ('despacho', 'Indicación de despacho')], default='nota', max_length=10)),
                ('texto', models.TextField()),
                ('creada', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_orden', to='core.persona')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='operaciones.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Nota de la orden',
                'verbose_name_plural': 'Notas de las órdenes',
                'ordering': ['-creada'],
            },
        ),
    ]
