# Generated by Django 5.2.18 on 2026-10-07 21:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_parametros_destinatarios_parte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('obligatorio_tecnicos', models.BooleanField(default=False)),
                ('obligatorio_supervisores', models.BooleanField(default=False)),
                ('dias_aviso', models.PositiveIntegerField(default=30, help_text='Avisar con esta anticipación al vencimiento.')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('accidente', 'Accidente laboral (ART)'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia especial (examen, mudanza, familiar…)'), ('franco', 'Franco compensatorio'), ('injustificada', 'Ausencia injustificada'), ('suspension', 'Suspensión')], max_length=15)),
                ('desde', models.DateField(default=django.utils.timezone.localdate)),
                ('hasta', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobar'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('certificado', models.FileField(blank=True, upload_to='certificados/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_cargadas', to='core.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='core.persona')),
            ],
            options={
                'verbose_name': 'Novedad / licencia',
                'verbose_name_plural': 'Novedades / licencias',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('emision', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, upload_to='legajos/%Y/')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento del legajo',
                'verbose_name_plural': 'Documentos del legajo',
                'ordering': ['vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('lat_entrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_entrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origen', models.CharField(choices=[('app', 'App (celular)'), ('manual', 'Carga manual'), ('importado', 'Importado / reloj')], default='app', max_length=10)),
                ('minutos_tarde', models.PositiveIntegerField(default=0, editable=False)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=5)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=5)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.persona')),
            ],
            options={
                'verbose_name': 'Asistencia (fichada)',
                'verbose_name_plural': 'Asistencias (fichadas)',
                'ordering': ['-fecha', 'persona__apellido'],
                'unique_together': {('persona', 'fecha')},
            },
        ),
    ]
