# Generated by Django 5.2.18 on 2026-10-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='resuelta',
            field=models.DateTimeField(blank=True, help_text='Cuándo se aprobó o rechazó.', null=True),
        ),
    ]
